version: "3.8"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-restart-policy:
  restart: unless-stopped

services:
  api:
    <<: *logging

    build:
      context: ./api
      dockerfile: Dockerfile

    env_file:
    - .env

    environment:
      ORDIS_API_DB_HOST: "postgres"
      ORDIS_API_HOST: "0.0.0.0"
      ORDIS_API_OPENTELEMETRY_ENDPOINT: "http://tempo:4317"

    volumes:
    - ./api:/api

    ports:
    - "8000:8000"

    networks:
    - database-access
    - api-metrics
    - ordis

  bot:
    <<: *logging

    build:
      context: ./bot
      dockerfile: Dockerfile

    environment:
      API_URL: "http://api:8000"

    env_file:
    - .env

    depends_on:
    - api

    volumes:
    - ./bot:/bot

    networks:
    - ordis

networks:
  database-access:
    name: database-access
    external: true
  api-metrics:
    name: api-metrics
    external: true
  ordis:
    name: ordis
    external: true
