name: Build

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dir: ["api", "bot"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ matrix.dir }}
        file: ./${{ matrix.dir }}/Dockerfile
        push: true
        cache-from: type=registry,ref=ghcr.io/xithrius/ordis/${{ matrix.dir }}:latest
        cache-to: type=inline
        tags: |
          ghcr.io/xithrius/ordis/${{ matrix.dir }}:${{ github.sha }}
          ghcr.io/xithrius/ordis/${{ matrix.dir }}:latest
        build-args: |
          git_sha=${{ github.sha }}
